version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/argo-api
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: argo-api-before.sh
      runas: root
  AfterInstall:
    - location: argo-api-stop.sh
      runas : root
  ApplicationStart:
    - location: argo-api-start.sh
      runas : root