version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - gradle build -x test
  post_build:
    commands:
      - mkdir build-out
      - mv argo-common/build/libs/*.jar build-out
      - mv argo-api/build/libs/*.jar build-out
      - mv argo-collector/build/libs/*.jar build-out
      - mv appspec.yml build-out
      - mv argo-api-start.sh build-out
      - mv argo-api-stop.sh build-out
      - mv argo-api-before.sh build-out
      - zip argo-api-build.zip -j build-out/*
artifacts:
  files:
    - '*.zip'
#    - 'argo-common/build/libs/*'
#    - 'argo-api/build/libs/*.jar'