datasource:
  argo:
    jdbc-url: 'jdbc:postgresql://argo-db.cnkxzmhdcjyk.ap-northeast-2.rds.amazonaws.com:5432/argo'
    username: 'argo'
    password: 'argo2020'
    driver-class-name: 'org.postgresql.Driver'

spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        hibernate:
          default_schema: public
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: contact@argoport.com
    password: argo2020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  data:
    cassandra:
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      consistency-level: one
      contact-points: localhost
      keyspace-name: argo
      username: argo
      password: argo2020

  jackson:
    serialization:
      fail-on-empty-beans: false

webdriver:
  chrome:
    driver: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

  profiles:
    active: local

server:
  port: 10002

file:
  upload:
    default-path: C:/attachements
    index: excel_upload

elasticsearch:
#  hosts: http://15.164.111.122:9200
  hosts: http://localhost:9200
registration:
  url:
    confirm: https://argoport.com/#/auth/confirm
    additional-info: https://argoport.com/#/auth/additional-info

aws:
  s3:
    accessKey: AKIAY7LXOLNEKJ4LQANO
    secretKey: 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

goData:
  token: v8N7GVyY1dKTJ8inAiv3lBPbajbHgjl8NAYSu1vKXvMCBUU2JhuQee8VyFVcS%2Bt37rZ1h9N9PktQeQRxjtUsnw%3D%3D
  url: http://apis.data.go.kr/B552015/NpsBplcInfoInqireService/getBassInfoSearch

passwordreset:
  url:
    confirm: https://argoport.com/#/auth/resetPasswordConfirm
