version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/argo-collector
hooks:
  BeforeInstall:
    - location: config/argo-collector-before.sh
      runas: root
  AfterInstall:
    - location: config/argo-collector-stop.sh
      runas : root
  ApplicationStart:
    - location: config/argo-collector-start.sh
      runas : root